# Inputs

In [ ]:
#Programa para dividir un número entre 6. 

num=input("Digita un número: ") #Tomamos primero el input del usuario

num_dividido_6=int(num)/6 #Importante esto, hay que convertir el número a entero con int(), ya que los inputs siempre se toman como strings

print("El número dividido entre 6 es "+str(num_dividido_6))


Digita un número: 15
El número dividido entre 6 es 2.5


# Try-except (Try-catch)

In [ ]:
# Bloque try/except: permite manejar errores sin que el programa se detenga.
# except captura el error y define qué hacer en ese caso.

#Programa para calcular cuál es mi edad en meses

try:
  edad_años_string=input("Digita tu edad en años ")
  edad_años_int=int(edad_años_string)
  edad_meses=edad_años_int*12
  print("Tu edad en meses es "+str(edad_meses))

except:
  print("No digitaste un número válido, intenta de nuevo")


Digita tu edad en años cincuenta
No digitaste un número válido, intenta de nuevo


In [ ]:
#Diferencia con el if-else, el cual no se utiliza cuando queremos capturar errores en Python, sino cuando queremos implementar
#alguna lógica en nuestro programa

#If - else

nombre = input("Digita tu nombre ")

if nombre[0].isupper():
  print("Tu nombre empieza con mayúscula")
else:
  print("Tu nombre no empieza con mayúscula")

Digita tu nombresantiago
Tu nombre no empieza con mayúscula


# List comprehensions

Las list comprehensions en Python son una forma concisa y expresiva de crear listas a partir de secuencias (listas, rangos, etc.) aplicando operaciones o condiciones, en una sola línea de código.

[nueva_expresión for elemento in iterable if condición]

In [ ]:
numeros=[x**5 for x in range (1,11) if x%2==0]

print(numeros)


[32, 1024, 7776, 32768, 100000]


# Numpy

In [ ]:
#Siempre imprtamos numpy como np
import numpy as np

In [ ]:
#Creamos una lista de números
lista_numeros=[1,2,4,5,7]

#Con esta línea la convertimos en un array de Numpy
array_numeros=np.array(lista_numeros)

#Veamos la clase de cada una
print(type(array_numeros))
print(type(lista_numeros))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
#Matrices de dos dimensiones en Numpy, así se crean:

matriz=np.array([[1,4,5],[6,7,8],[7,2,3]])

#Función para ver las tamaño de una matriz
print(matriz.shape)

#Función para ver la dimensión de la matriz
print(matriz.ndim)

#Función para ver el número de elementos
print(matriz.size)

#Función para saber el tamaño de la matriz
print(matriz.nbytes)

print(matriz)

(3, 3)
2
9
72
[[1 4 5]
 [6 7 8]
 [7 2 3]]


In [ ]:
#Acceder a los elementos de la matriz
#EL ÍNDICE COMIENZA POR CERO (0)
print(matriz[1,2])

8


In [ ]:
#Obtener una fila específica
print(matriz[0,:])

[1 4 5]


In [ ]:
#Obtener una columna específica
print(matriz[:,1])

[4 7 2]


In [ ]:
#Cambiar toda la primera fila de la matríz por [0,0,0]
matriz[0,:]=[0,0,0]

print(matriz)

[[0 0 0]
 [6 7 8]
 [7 2 3]]


In [ ]:
#Crear una atriz identidad  4x4
matriz_identidad=np.identity(5)

print(matriz_identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Crear una matriz llena de ceros
matriz_nula=np.zeros((6,3))

print(matriz_nula)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Crear una matriz llena de otro número arbitrario
matriz_arbitraria=np.full((3,8),100)

print(matriz_arbitraria)

[[100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]]


In [ ]:
#Matriz llena de números aleatorios (enteros)
matriz_numeros_aleatorios=np.random.randint(5,10,(15,15))

print(matriz_numeros_aleatorios)

[[5 6 9 9 5 9 5 8 6 6 5 6 5 5 6]
 [5 9 5 6 6 5 8 6 9 7 7 7 7 8 9]
 [5 6 9 8 8 6 7 7 7 9 8 6 5 6 7]
 [6 5 8 9 9 9 8 8 9 8 7 9 5 9 9]
 [6 9 5 9 8 9 8 9 8 6 5 5 9 6 5]
 [5 7 8 8 5 7 8 5 6 7 9 9 8 9 7]
 [8 8 6 5 6 7 8 7 9 9 9 6 9 5 9]
 [9 6 5 5 5 7 9 5 9 5 6 6 7 6 5]
 [8 5 6 7 5 5 7 6 5 6 7 6 6 9 7]
 [6 6 5 9 8 9 5 9 9 5 6 8 5 5 9]
 [6 7 7 7 8 6 7 8 7 5 5 9 8 5 6]
 [9 8 8 9 9 5 5 5 6 5 7 6 7 5 8]
 [7 5 6 9 7 5 8 8 7 5 9 8 9 6 8]
 [9 9 8 5 8 5 9 8 8 5 8 9 6 7 9]
 [9 6 7 6 8 5 7 5 6 6 8 8 9 6 7]]


In [ ]:
#Matriz llena de números aleatorios (de 0 a 1)
matriz_numeros_aleatorios=np.random.rand(5,2)

print(matriz_numeros_aleatorios)

[[0.3686418  0.7788886 ]
 [0.27521423 0.34996249]
 [0.15858304 0.40441742]
 [0.5089535  0.61766665]
 [0.31145082 0.51652232]]


In [ ]:
#Multiplicación de matrices

matriz_1=np.array([[1,90],[5,67]])
matriz_2=np.array([[3,4],[5,6]])

multiplicacion= matriz_1*matriz_2

print(matriz_1)
print(matriz_2)
print(multiplicacion)

#Operaciones de algebra lineal con las matrices
print(np.matmul(matriz_1,matriz_2))
print(np.linalg.det(matriz_1))
print(np.linalg.inv(matriz_1))


[[ 1 90]
 [ 5 67]]
[[3 4]
 [5 6]]
[[  3 360]
 [ 25 402]]
[[453 544]
 [350 422]]
-382.9999999999999
[[-0.17493473  0.23498695]
 [ 0.01305483 -0.00261097]]


In [ ]:
#Operaciones estadísticas

datos_altura=np.random.randint(150,195,(20))

print(datos_altura)

#Media
media=np.mean(datos_altura)

#Mediana
mediana=np.median(datos_altura)

#Desviación estándar
devest=np.std(datos_altura)

#Valor mínimo
minimo=np.min(datos_altura)

#Valor máximo
maximo=np.max(datos_altura)

#Percentil 75
percentil_75=np.percentile(datos_altura,75)

print(media)
print(mediana)
print(devest)
print(minimo)
print(maximo)
print(percentil_75)

[184 182 165 192 184 193 179 167 176 187 173 176 189 185 151 183 150 176
 161 189]
177.1
180.5
12.28779882647824
150
193
185.5


In [ ]:
from scipy.stats import kurtosis, skew

print(skew(datos_altura))
print(kurtosis(datos_altura))

-0.8511121803854064
-0.20179685129210245


In [ ]:

#Quiero traer las personas con altura mayor a 170

print(datos_altura[datos_altura>170])

[150]


In [ ]:
#Array de nacionalidades
nacionalidades=np.array(["Colombiano","Colombiano","Colombiano","Colombiano","Argentino", "Peruano", "Colombiano","Colombiano","Mexicano", "Mexicano"])

In [ ]:
print(nacionalidades[nacionalidades=="Colombiano"])

['Colombiano' 'Colombiano' 'Colombiano' 'Colombiano' 'Colombiano'
 'Colombiano']
